# Generated by Django 3.1.4 on 2021-05-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_config', '0001_initial'),
        ('new_door', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('next_paid_date', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('remain_amount', models.PositiveIntegerField()),
                ('remarks', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantcontract')),
                ('pay_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_config.paymodetype')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.unit')),
            ],
        ),
    ]
