# Generated by Django 3.1.4 on 2021-04-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractReqType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_req', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_type', models.CharField(max_length=50)),
                ('num_of_doc', models.IntegerField(default=2)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50, unique=True)),
                ('contact_no', models.CharField(max_length=20, unique=True)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pobox', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccupancyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_type', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayModeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('pcontact', models.CharField(max_length=254)),
                ('scontact', models.CharField(max_length=254)),
                ('marital_status', models.CharField(choices=[('', 'Select marital status'), ('Married', 'Married'), ('Single', 'Single')], max_length=50)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('is_tenant', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pobox', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('contact_no', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(max_length=254)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.entity')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.categorytype')),
            ],
        ),
        migrations.CreateModel(
            name='StatusReqType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_req', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantReqType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_req_type', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.CharField(max_length=250)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('parking', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
                ('occupancy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.occupancytype')),
                ('ownership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.ownershiptype')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.property')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.documenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_image', models.ImageField(upload_to='unit')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.unit')),
            ],
        ),
        migrations.CreateModel(
            name='TenantContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('annual_rent', models.PositiveIntegerField(blank=True, null=True)),
                ('security_dep', models.PositiveIntegerField(blank=True, null=True)),
                ('commission', models.PositiveIntegerField(blank=True, null=True)),
                ('installments', models.PositiveIntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, max_length=550, null=True)),
                ('sms_notify', models.BooleanField(default='False')),
                ('email_notify', models.BooleanField(default='False')),
                ('contract_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.contractreqtype')),
                ('contract_status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.statusreqtype')),
                ('property_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.profile')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new_door.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('next_paid_date', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('remain_amount', models.PositiveIntegerField()),
                ('remarks', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.tenantcontract')),
                ('pay_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.paymodetype')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.unit')),
            ],
        ),
        migrations.AddField(
            model_name='contractreqtype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.profile'),
        ),
    ]
