# Generated by Django 3.1.4 on 2021-05-30 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50, unique=True)),
                ('contact_no', models.CharField(max_length=20, unique=True)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=50)),
                ('po_box', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=50)),
                ('po_box', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('contact_no', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(max_length=254)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.entity')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.CharField(max_length=250)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('parking', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, max_length=550, null=True)),
                ('occupancy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_config.occupancytype')),
                ('ownership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_config.ownershiptype')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.property')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_config.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_image', models.ImageField(upload_to='unit')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.unit')),
            ],
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_config.documenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
