# Generated by Django 3.1.3 on 2020-11-23 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='ContractReqType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_req_type', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(default='', max_length=20)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('pobox', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('desc', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='OccupancyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='PayModeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('property_name', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('pobox', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=254)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.entity')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=550)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.categorytype')),
            ],
        ),
        migrations.CreateModel(
            name='StatusReqType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_qty', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='TenantReqType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_req_type', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.CharField(max_length=250)),
                ('rent_amount', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('bedrooms', models.CharField(max_length=50)),
                ('bathrooms', models.CharField(max_length=30)),
                ('parking', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=550)),
                ('occupancy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.occupancytype')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.property')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.propertytype')),
                ('pwner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.ownershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_image', models.ImageField(upload_to='pictures')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.unit')),
            ],
        ),
        migrations.CreateModel(
            name='TenantContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=50)),
                ('start_date', models.DateField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('annual_rent', models.CharField(max_length=50)),
                ('security_dep', models.CharField(max_length=50)),
                ('commission', models.CharField(max_length=50)),
                ('installments', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=550)),
                ('sms_notify', models.BooleanField(default='False')),
                ('email_notify', models.BooleanField(default='False')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.property')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('pcontact', models.CharField(max_length=254)),
                ('scontact', models.CharField(max_length=254)),
                ('marry_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=50)),
                ('nationality', models.CharField(max_length=254)),
                ('roll_id', models.CharField(max_length=254)),
                ('is_tenant', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
