# Generated by Django 3.1.3 on 2020-11-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0002_auto_20201124_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractreqtype',
            name='contract_req_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contractreqtype',
            name='desc',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='entity',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymodetype',
            name='desc',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='statusreqtype',
            name='desc',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='statusreqtype',
            name='str_qty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantreqtype',
            name='desc',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='tenantreqtype',
            name='tenant_req_type',
            field=models.CharField(max_length=50),
        ),
    ]
