# Generated by Django 3.1.4 on 2021-02-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0002_payment_next_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='next_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
