# Generated by Django 3.1.3 on 2020-11-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0002_auto_20201126_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_vacant',
            field=models.BooleanField(default=False),
        ),
    ]
