# Generated by Django 3.1.3 on 2020-11-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0003_auto_20201125_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='marry_status',
            new_name='marital_status',
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='unit_image',
            field=models.ImageField(upload_to='unit'),
        ),
    ]
