# Generated by Django 3.1.3 on 2020-12-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0003_unit_is_vacant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
