# Generated by Django 3.1.4 on 2021-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0003_auto_20210202_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
