# Generated by Django 3.1.3 on 2020-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0004_auto_20201125_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractReqType',
        ),
        migrations.DeleteModel(
            name='DocumentsType',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='PayModeType',
        ),
        migrations.DeleteModel(
            name='StatusReqType',
        ),
        migrations.RemoveField(
            model_name='tenantcontract',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='tenantcontract',
            name='unit_id',
        ),
        migrations.DeleteModel(
            name='TenantReqType',
        ),
        migrations.RenameField(
            model_name='propertytype',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='pwner_type',
            new_name='owner_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='desc',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='occupancytype',
            name='desc',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='ownershiptype',
            name='desc',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='desc',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='property_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='desc',
            field=models.TextField(max_length=550),
        ),
        migrations.DeleteModel(
            name='TenantContract',
        ),
    ]
