# Generated by Django 3.1.4 on 2020-12-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0004_auto_20201203_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=50)),
                ('start_date', models.DateField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('annual_rent', models.CharField(max_length=50)),
                ('security_dep', models.CharField(max_length=50)),
                ('commission', models.CharField(max_length=50)),
                ('installments', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=550)),
                ('sms_notify', models.BooleanField(default='False')),
                ('email_notify', models.BooleanField(default='False')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.profile')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ContractReqType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_req', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=550)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.profile')),
            ],
        ),
    ]
