# Generated by Django 3.1.4 on 2021-02-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0004_property_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='total_amount',
        ),
    ]
