# Generated by Django 3.1.4 on 2020-12-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0006_documenttype_paymodetype_statusreqtype_tenantreqtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusreqtype',
            old_name='str_qty',
            new_name='str_req',
        ),
    ]
