# Generated by Django 3.1.4 on 2020-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0007_auto_20201205_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='contact_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pcontact',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scontact',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_no',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
