# Generated by Django 3.1.4 on 2021-02-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0008_payment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='num_of_doc',
            field=models.IntegerField(default=0),
        ),
    ]
