# Generated by Django 3.1.4 on 2021-02-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0009_documenttype_num_of_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='num_of_doc',
            field=models.IntegerField(default=2),
        ),
    ]
