# Generated by Django 3.1.4 on 2020-12-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0009_auto_20201206_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_vacant',
        ),
    ]
