# Generated by Django 3.1.4 on 2020-12-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0011_auto_20201207_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pcontact',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scontact',
            field=models.CharField(max_length=254),
        ),
    ]
