# Generated by Django 3.1.4 on 2020-12-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0012_auto_20201208_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rent_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
