# Generated by Django 3.1.4 on 2020-12-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0015_auto_20201210_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
