# Generated by Django 3.1.4 on 2020-12-10 22:17

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0016_auto_20201210_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
