# Generated by Django 3.1.4 on 2020-12-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0018_auto_20201210_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roll_id',
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='cat_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='desc',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='contractreqtype',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='occupancytype',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='ownershiptype',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='paymodetype',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mid_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='statusreqtype',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='annual_rent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='contract_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='remark',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenantreqtype',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='desc',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
    ]
