# Generated by Django 3.1.4 on 2020-12-10 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0019_auto_20201210_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
