# Generated by Django 3.1.4 on 2020-12-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0021_auto_20201210_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic'),
        ),
    ]
