# Generated by Django 3.1.4 on 2020-12-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0024_auto_20201217_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantcontract',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
