# Generated by Django 3.1.4 on 2020-12-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0026_auto_20201217_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontract',
            name='annual_rent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='commission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='contract_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='installments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='remark',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='security_dep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
