# Generated by Django 3.1.4 on 2020-12-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0027_auto_20201217_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontract',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.property'),
        ),
    ]
