# Generated by Django 3.1.4 on 2020-12-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0028_auto_20201217_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.profile'),
        ),
    ]
