# Generated by Django 3.1.4 on 2020-12-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0029_auto_20201218_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcontract',
            name='contract_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.contractreqtype'),
        ),
    ]
