# Generated by Django 3.1.4 on 2020-12-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0030_tenantcontract_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcontract',
            name='contract_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.contractreqtype'),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='contract_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.statusreqtype'),
        ),
    ]
