# Generated by Django 3.1.4 on 2020-12-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0032_documentimage_uploaddocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentimage',
            old_name='product',
            new_name='upload_doc',
        ),
    ]
