# Generated by Django 3.1.4 on 2020-12-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0033_auto_20201218_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentimage',
            old_name='upload_doc',
            new_name='doc_type',
        ),
    ]
