# Generated by Django 3.1.4 on 2020-12-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0034_auto_20201219_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentimage',
            name='default',
        ),
    ]
