# Generated by Django 3.1.4 on 2020-12-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0035_remove_documentimage_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentImage',
        ),
    ]
