# Generated by Django 3.1.4 on 2020-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0036_delete_documentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
