# Generated by Django 3.1.4 on 2020-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0037_uploaddocument_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
