# Generated by Django 3.1.4 on 2020-12-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0038_auto_20201221_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='doc_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new_door.documenttype'),
        ),
        migrations.CreateModel(
            name='VerifiedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.profile')),
            ],
        ),
    ]
