# Generated by Django 3.1.4 on 2020-12-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0039_auto_20201221_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_door.documenttype'),
        ),
    ]
