# Generated by Django 3.1.4 on 2020-12-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0040_auto_20201221_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifiedDocument',
        ),
    ]
