# Generated by Django 3.1.4 on 2020-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0041_delete_verifieddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocument',
            name='desc',
            field=models.TextField(default='Hi there'),
            preserve_default=False,
        ),
    ]
