# Generated by Django 3.1.4 on 2020-12-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0042_uploaddocument_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
