# Generated by Django 3.1.4 on 2021-01-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0045_auto_20210120_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remain_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
