# Generated by Django 3.1.4 on 2021-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0046_auto_20210120_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontract',
            name='commission',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontract',
            name='security_dep',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
