# Generated by Django 3.1.4 on 2021-01-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0047_auto_20210120_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_door.paymodetype'),
        ),
    ]
