# Generated by Django 3.1.4 on 2021-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0048_auto_20210120_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
