# Generated by Django 3.1.4 on 2021-01-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0051_auto_20210120_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontract',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
