# Generated by Django 3.1.4 on 2021-01-31 16:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('new_door', '0054_auto_20210131_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
