# Generated by Django 3.1.4 on 2021-05-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0001_initial'),
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_details', models.TextField()),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('reference_no', models.CharField(max_length=10)),
                ('review', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantcontract')),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_config.statusreqtype')),
                ('tenant_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_config.tenantreqtype')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_num', models.CharField(max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
