# Generated by Django 3.1.4 on 2021-05-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('app_config', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintenance',
            new_name='MaintenanceRequest',
        ),
    ]
